setup/urls.py
from django.urls import path
from chamados.views import *
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

urlpatterns = [
    path("admin/", admin.site.urls, name="admin"),
    path('chamados/', ChamadoListView.as_view(), name='chamado-list'),
    path('chamados/<int:pk>/', ChamadoDetailView.as_view(), name='chamado-detail'),
    path('chamados/new/', ChamadoCreateView, name='chamado-create'),
    path('chamados/<int:pk>/update/', chamado_edit, name='chamado-update'),
    # path('chamados/<int:pk>/update/', view_chamado, name='chamado-update'),
    path('chamados/<int:pk>/delete/', ChamadoDeleteView, name='chamado-delete'),
    path('setores/', SetorListView.as_view(), name='setor-list'),
    path('setores/<int:pk>/', SetorDetailView.as_view(), name='setor-detail'),
    path('usuarios/', UsuarioListView.as_view(), name='usuario-list'),
    path('usuarios/<int:pk>/', UsuarioDetailView.as_view(), name='usuario-detail'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', home, name='home'),
    path('setor/new/', cadastrar_setor, name='cadastrar_setor'),
    path('setor/existente/', setor_existente, name='setor_existente'),
    path('setor/editar/<int:setor_id>/', editar_setor, name='editar_setor'),
    path('setor/excluir/<int:setor_id>/', excluir_setor, name='excluir_setor'),
    path('chamado/atualizar/<int:chamado_id>/', atualizar_chamado, name='atualizar_chamado'),
    path('chamados-nao-atendidos/', listar_chamados_nao_atendidos, name='listar_chamados_nao_atendidos'),
    path('chamados-por-mes/', chamados_por_mes, name='chamados_por_mes'),
    path('tempo-medio-atendimento/', tempo_medio_atendimento, name='tempo_medio_atendimento'),
]

chamados/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
class Setor(models.Model):
    nome = models.CharField(max_length=100)

    def __str__(self):
        return self.nome

class Usuario(AbstractUser):
    # setor = models.ForeignKey(Setor, on_delete=models.CASCADE)
    setor = models.ForeignKey(Setor, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.username

class Chamado(models.Model):
    titulo = models.CharField(max_length=100)
    descricao = models.TextField()
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name='chamados')
    setor = models.ForeignKey(Setor, on_delete=models.CASCADE)
    data = models.DateField()
    hora_chamado = models.TimeField(null=True, blank=True)
    data_cadastro = models.DateTimeField(auto_now_add=True)
    tecnico = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name='chamados_atendidos', null=True, blank=True)
    atendido = models.BooleanField(default=False)
    data_atendimento = models.DateField(null=True, blank=True)
    hora_atendimento = models.TimeField(null=True, blank=True)
    def __str__(self):
        return self.titulo

chamados/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth.forms import UserCreationForm
from .models import Usuario, Chamado, Setor
from django.contrib.auth.models import User
class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = Usuario
        fields = ['username', 'email', 'password1', 'password2']
class ChamadoForm(forms.ModelForm):
    class Meta:
        model = Chamado
        fields = ['titulo', 'descricao', 'setor', 'data','hora_chamado', 'usuario']
        widgets = {
            'data': forms.DateInput(attrs={'type': 'date'}),
            'descricao': forms.Textarea(attrs={'rows': 5}),
            'hora_chamado': forms.TimeInput(attrs={'type': 'time'}),
        }
        labels = {
            'hora_chamado': 'Horario',
        }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance and self.instance.data:
            self.initial['data'] = self.instance.data.strftime('%Y-%m-%d')
class SetorForm(forms.ModelForm):
    class Meta:
        model = Setor
        fields = ['nome']

class AtualizarChamadoForm(forms.ModelForm):
    class Meta:
        model = Chamado
        fields = ['atendido', 'data_atendimento', 'hora_atendimento', 'tecnico']
        widgets = {
            'data_atendimento': forms.DateInput(format = settings.DATETIME_FORMAT, attrs={'type': 'date'}),
            'hora_atendimento': forms.TimeInput(attrs={'type': 'time'}),
        }
class Chamado_Editar_Form(forms.Form):
    class Meta:
        model = Chamado
        fields = ['titulo', 'descricao', 'setor', 'data', 'usuario']
        widgets = {
            'data': forms.DateInput(attrs={'type': 'date'}),
            'descricao': forms.Textarea(attrs={'rows': 5}),
        }
    

chamados/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, DeleteView
from .models import Setor, Usuario, Chamado
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.utils import timezone
from .forms import CustomUserCreationForm, ChamadoForm, SetorForm, AtualizarChamadoForm
from django.contrib.auth import logout
from datetime import datetime
from django.db.models import Count
from django.db.models.functions import ExtractMonth, ExtractYear
import locale
from calendar import month_name  # Importe month_name aqui
# Definindo o idioma local como português do Brasil
locale.setlocale(locale.LC_TIME, 'pt_BR.UTF-8')
# from django import forms
# from datetime import datetime
################# Chamados ################
class ChamadoListView(ListView):
    model = Chamado
    template_name = 'chamado_list.html'

class ChamadoDetailView(DetailView):
    model = Chamado
    template_name = 'chamados/chamado_detail.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        chamado = self.get_object()  # Obtém o objeto Chamado
        context['chamado_keys'] = chamado.__dict__.keys()  # Obtém as chaves do objeto
        return context

@login_required(login_url='login')
def ChamadoCreateView(request):
    data = datetime.now().strftime('%Y-%m-%d')
    hora_atual = datetime.now().strftime("%H:%M")
    context = {}
    if request.method == "POST":
        form = ChamadoForm(request.POST)
        form.initial['hora_chamado'] = hora_atual
        form.initial['data'] = datetime.now().strftime('%Y-%m-%d')
        user = request.user
        context = {
            'form': form,
            'user': user,
        }
        if form.is_valid():
            form.save()
            return redirect("chamado-list")
    else:
        form = ChamadoForm()
        form.initial['hora_chamado'] = hora_atual
        form.initial['data'] = datetime.now().strftime('%Y-%m-%d')
        context['form'] = form
        context['data'] = data
    return render(request, "chamados/chamado_form.html", context)

@login_required(login_url='login')
def chamado_edit(request, pk):
    chamado = get_object_or_404(Chamado, pk=pk)
    if request.method == 'POST':
        form = ChamadoForm(request.POST, instance=chamado)
        if form.is_valid():
            form.save()
            return redirect('chamado-list')
    else:
        form = ChamadoForm(instance=chamado)
    return render(request, 'chamados/formularioeditar.html', {'form': form})

@login_required(login_url='login')
class ChamadoDeleteView(DeleteView):
    model = Chamado
    template_name = 'chamados/chamado_confirm_delete.html'
    success_url = reverse_lazy('chamado-list')

@login_required(login_url='login')
def atualizar_chamado(request, chamado_id):
    chamado = get_object_or_404(Chamado, pk=chamado_id)
    if request.method == 'POST':
        form = AtualizarChamadoForm(request.POST, instance=chamado)
        if form.is_valid():
            form.save()
            return redirect('listar_chamados_nao_atendidos')
    else:
        form = AtualizarChamadoForm(instance=chamado)
        # Se for a primeira vez que o formulário é exibido, defina o valor inicial da hora
        if not request.POST:
            form.initial['hora_atendimento'] = datetime.now().strftime('%H:%M')
            form.initial['data_atendimento'] = datetime.now().strftime('%Y-%m-%d')
    return render(request, 'chamados/atualizar_chamado.html', {'form': form})

@login_required(login_url='login')
def listar_chamados_nao_atendidos(request):
    chamados_nao_atendidos = Chamado.objects.filter(atendido=False)
    existe_chamado_nao_atendido = chamados_nao_atendidos.exists()
    return render(request, 'chamados/listar_chamados_nao_atendidos.html', {'chamados_nao_atendidos': chamados_nao_atendidos, 'existe_chamado_nao_atendido': existe_chamado_nao_atendido})
################ RELATORIO ################
def chamados_por_mes(request):
    chamados_por_mes = Chamado.objects.annotate(mes=ExtractMonth('data'), ano=ExtractYear('data')).values('mes', 'ano').annotate(total=Count('id'))
    meses_ano = [f"{month_name[mes['mes']]} {mes['ano']}" for mes in chamados_por_mes]
    totals = [mes['total'] for mes in chamados_por_mes]
    return render(request, 'chamados/chamados_por_mes.html', {'meses_ano': meses_ano, 'totals': totals})

def tempo_medio_atendimento(request):
    chamados_atendidos = Chamado.objects.filter(atendido=True).exclude(data_atendimento=None)
    tempos_atendimento = []
    for chamado in chamados_atendidos:
        data_hora_chamado = timezone.make_aware(timezone.datetime.combine(chamado.data, chamado.hora_chamado))
        data_hora_atendimento = timezone.make_aware(timezone.datetime.combine(chamado.data_atendimento, chamado.hora_atendimento))
        tempo_atendimento = data_hora_atendimento - data_hora_chamado
        tempos_atendimento.append(tempo_atendimento)
    return render(request, 'chamados/tempo_medio_atendimento.html', {'tempos_atendimento': tempos_atendimento})

class UsuarioListView(ListView):
    model = Usuario
    template_name = 'usuario/usuario_list.html'

class UsuarioDetailView(DetailView):
    model = Usuario
    template_name = 'usuario/usuario_detail.html'
class CustomLoginView(LoginView):
    template_name = 'registration/login.html'

class CustomLogoutView(LogoutView):
    next_page = reverse_lazy('login')

class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'
def logout_view(request):
    logout(request)
    return redirect('login')
def home(request):
    return render(request, 'outros/home.html')

########## SETOR ############'

class SetorListView(ListView):
    model = Setor
    template_name = 'setor/setor_list.html'

class SetorDetailView(DetailView):
    model = Setor
    template_name = 'setor/setor_detail.html'

@login_required(login_url='login')
def cadastrar_setor(request):
    if request.method == 'POST':
        form = SetorForm(request.POST)
        if form.is_valid():
            nome_setor = form.cleaned_data['nome']
            # Verifica se o setor já existe no banco de dados
            if Setor.objects.filter(nome=nome_setor).exists():
                return redirect('setor_existente')
            else:
                form.save()
                return redirect('setor-list')
    else:
        form = SetorForm()
    return render(request, 'setor/cadastrar_setor.html', {'form': form})
def editar_setor(request, setor_id):
    setor = get_object_or_404(Setor, pk=setor_id)
    if request.method == 'POST':
        form = SetorForm(request.POST, instance=setor)
        if form.is_valid():
            form.save()
            return redirect('setor_editado')
    else:
        form = SetorForm(instance=setor)
    return render(request, 'setor/editar_setor.html', {'form': form})

def excluir_setor(request, setor_id):
    setor = get_object_or_404(Setor, pk=setor_id)
    if request.method == 'POST':
        setor.delete()
        return redirect('setor_excluido')
    return render(request, 'excluir_setor.html', {'setor': setor})

def setor_existente(request):
    return render(request, 'setor/setor_existente.html')

def view_chamado(request, pk):
    chamado = get_object_or_404(Chamado, pk=pk)
    if request.method == "POST":
        form = ChamadoForm(request.POST, instance=chamado)
        if form.is_valid():
            form.save()
            return redirect("chamado-list")
    else:
        form = ChamadoForm(instance=chamado)
    return render(request, "chamados/chamado_form.html", {'form': form})
    chamado = Chamado.objects.get(pk=pk)
    data = chamado.data.strftime('%Y-%m-%d')#YYYY-MM-DD
    form = ChamadoForm(instance=chamado)
    context = {'chamado': chamado, 'data': data}
    context['form'] = form
    return render(request, 'chamados/chamado_edit.html', context)

chamados/templates/chamados/atualizar_chamado.html
{% extends 'base.html' %}
{% load static %}

{% block page_title %}Atualizar Chamado{% endblock page_title %}

{% block content %}
<div class="container">
    <h1>Atualizar Chamado</h1>
    <form method="post"  class="row gy-2 gx-3 align-items-center">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="col-12">
        <button type="submit" class="btn btn-primary">Salvar</button>
        </div>
    </form>
</div>
{% endblock content %}

chamados/templates/chamados/chamado_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirmação de Deleção de Chamado</title>
</head>
<body>
    <h1>Confirmação de Deleção de Chamado</h1>
    <p>Você tem certeza que deseja deletar o chamado "{{ object }}"?</p>
    <form method="POST">
        {% csrf_token %}
        <button type="submit">Sim, deletar</button>
    </form>
    <a href="{% url 'chamado-list' %}">Cancelar</a>
</body>
</html>

chamados/templates/chamados/chamado_detail.html
{% extends 'base.html' %}
{% load static %}

{% block page_title %}Chamado Detalhes{% endblock page_title %}

{% block content %}
<div class="container">
<table style="border: 1px solid black;margin-left: 10px;">
    <tr style="border: 1px solid black;">
        <th colspan="2" style="text-align: center; border: 1px solid black;"><h2>Chamado Detalhes</h2></th>
    </tr>
    <tr style="border: 1px solid black;"><th style="border: 1px solid black;">ID</th><td style="padding-left: 10px;">{{ object.pk }}</th></tr>
    <tr style="border: 1px solid black;"><th style="border: 1px solid black;">Título</th><td style="padding-left: 10px;">{{ object.titulo }}</td></tr>
    <tr style="border: 1px solid black;"><th style="border: 1px solid black;">Descrição</th><td style="padding-left: 10px;">{{ object.descricao }}</td></tr>
    <tr style="border: 1px solid black;"><th style="border: 1px solid black;">Usuário</th><td style="padding-left: 10px;">{{ object.usuario }}</td></tr>
    <tr style="border: 1px solid black;"><th style="border: 1px solid black;">Setor</th><td style="padding-left: 10px;">{{ object.setor }}</td></tr>
    <tr style="border: 1px solid black;"><th style="border: 1px solid black;">Data</th><td style="padding-left: 10px;">{{ object.data }}</td></tr>
    <tr style="border: 1px solid black;"><th style="border: 1px solid black;">Horario</th><td style="padding-left: 10px;">{{ object.hora_chamado }}</td></tr>
    {% if object.tecnico == None %}<tr><th></th><td></td></tr>{% else %}<tr><th>Técnico</th><td style="padding-left: 10px;">{% endif %}</td></tr>
    <tr style="border: 1px solid black;"><th style="border: 1px solid black;">Atendido</th><td style="padding-left: 10px;">{% if object.atendido %} Sim {% else %} Não {% endif %}</td></tr>
    <tr style="border: 1px solid black;"><th style="border: 1px solid black;text-align: center;">
        <a href="{% url 'chamado-update' object.pk %}">Editar</a>
    </th>
    <th style="border: 1px solid black;text-align: center;">
        <a href="{% url 'chamado-delete' object.pk %}">Deletar</a>

    </th>
</tr>
</table>
</div>
{% endblock content %}

chamados/templates/chamados/chamado_edit.html
<-- chamados/chamado_edit.html -->
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        
    </head>
    <body>
        <title>Formulario de Edição</title>
    </head>
  <body>
      <div class="container">
        <h1>Formulario de Edição</h1>
	<form method="post" action="{% url 'chamado-update' chamado.id %}">
    {% csrf_token %}
    <input type="text" name="id" id="id_id" value="{{ chamado.id }}" style="display: none;">
    <table class="table table-striped">
  <thead>
    <tr>
      <th scope="col"><label for="titulo">Titulo</label></th>
      <th scope="col"><input type="text" name="titulo" id="id_titulo" value="{{ chamado.titulo }}"></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row"><label for="descricao">Descrição</label></th>
      <td><textarea id="id_descricao" rows="5">{{ chamado.descricao }}</textarea></td>
    </tr>
    <tr>
      <th scope="row"><label for="setor">Setor</label></th>
      <td><select name="setor" id="id_setor">
        {% for setor in setores %}
        <option value="{{ setor.id }}" {% if setor.id == chamado.setor.id %} selected {% endif %}>{{ setor.nome }}</option>
    {% endfor %}
      </select></td>
    </tr>
    <tr>
        <th scope="row"><label for="data">Data:</label></th>
        <td><input type="date" name="data" id="id_data"></td>
      </tr>
      <tr>
        <th scope="row"><label for="usauario">Usuario:</label></th>
        <td><select name="setor" id="id_setor">
            {% for usuario in usuarios %}
            <option value="{{ usuario.id }}" {% if usuario.id == chamado.usuario.id %} selected {% endif %}>{{ usuario }}</option>
        {% endfor %}
          </select></td>
      </tr>
    <tr>
    	<th colspan="2">
    <button type="submit">Salvar Alterações</button>		
    	</th>
    </tr>
  </tbody>
</table>
</form>
</div>
Usuarios {{ chamado.usuario }}
<script>
    var DataJango = '{{ chamado.data|date:"Y-m-d" }}';
    document.getElementById('id_data').value = DataJango
    // Obtenha o nome do usuário do Django
    var nomeUsuario = '{{ chamado.usuario }}';

    // Obtenha todas as opções do select
    var options = document.getElementById('id_usuario').options;

    // Itere sobre as opções e defina a selecionada com base no nome do usuário
    for (var i = 0; i < options.length; i++) {
        if (options[i].text === nomeUsuario) {
            options[i].selected = true;
            break; // Saia do loop depois de encontrar a correspondência
        }
    }
</script>
	
</body>
</html>

chamados/templates/chamados/chamado_form.html
<!-- templates/financas/adicionar_receita.html -->
{% extends 'base.html' %}
{% load static %}

{% block page_title %}
    
Adicionar Chamado
{% endblock page_title %}
    

{% block content %}
<div class="pai">
    <div class="filho">
        <table class="tabela-cor">
            <form method="post" action="{% url 'chamado-create' %}">
                {% csrf_token %}
                <tr>
                    <th colspan="2" style="text-align: center">
                    <h2>Adicionar Chamado</h2><br>

                </th>
            </tr>
                {% for field in form %}
                <tr>
                    <td style="text-align: right;font-weight: bold;font-style: italic;">{{ field.label_tag }}</td>
                    <td style="text-align: left;">{{ field }}</td>
                </tr>
                {% endfor %}
            </table>
            <button type="submit">Salvar</button>
        </form>
        <br>
        <a href="{% url 'chamado-list' %}">Voltar para Lista de Chamados</a>
    </div>
</div>
<script>
    // Valor obtido do Django
    var valorDjango = "{{ user.pk }}";

    // Seleciona o elemento select
    var selectElement = document.getElementById('id_usuario');

    // Percorre as opções do select
    for (var i = 0; i < selectElement.options.length; i++) {
        // Se o valor da opção for igual ao valor do Django, define como selecionada
        if (selectElement.options[i].value === valorDjango) {
            selectElement.selectedIndex = i;
            break;
        }
    }
    var dataDjango = "{{ data }}";
    document.getElementById("id_data").value = dataDjango
    // Pegando a hora enviada pela view Django
    var dataDjango = "{{ data }}";
    // Converter a data para o formato HH:MM:SS
    var dataFormatada = new Date(dataDjango).toLocaleTimeString();
    // Definir o valor no campo time
    document.getElementById("id_data").value = dataFormatada;
</script>


{% endblock content %}

chamados/templates/chamados/chamado_list.html
{% extends 'base.html' %}

{% block page_title %}
Lista de Chamados
{% endblock page_title %}
    

{% block content %}
    

<h1>Lista de Chamados</h1>
<table class="table table-striped">
    {% for chamado in object_list %}
    <tr><th>
        <ul style="list-style-type: disc;">
        <li><a href="{% url 'chamado-detail' chamado.pk %}">{{ chamado.titulo }}</a></li>
    </th></tr>
    {% endfor %}
    </ul>
    <br>
</table>
<a href="{% url 'chamado-create' %}" class="btn btn-primary" style="margin-left: 10px;">Novo Chamado</a>
{% endblock content %}

chamados/templates/chamados/chamados_por_mes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chamados por Mês</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>
    <h1>Chamados por Mês</h1>
    <canvas id="myChart" width="400" height="400"></canvas>

    <script>
        var ctx = document.getElementById('myChart').getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: {{ meses_ano|safe }},
                datasets: [{
                    label: 'Chamados por Mês',
                    data: {{ totals|safe }},
                    backgroundColor: 'rgba(54, 162, 235, 0.2)',
                    borderColor: 'rgba(54, 162, 235, 1)',
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        }
                    }]
                }
            }
        });
    </script>
</body>
</html>

chamados/templates/chamados/formularioeditar.html
{% extends 'base.html' %}
{% load static %}

{% block page_title %}Editar Chamado{% endblock page_title %}

{% block content %}
<div class="container">
<form method="post">
  {% csrf_token %}
  <table class="table table-striped">
    <tr><td colspan="2"><h1>Editar Chamado</h1></td></tr>
    {% for field in form %}
      <tr>
        <td>{{ field.label_tag }}</td>  <!-- Renderiza o label do campo -->
        <td>{{ field }}</td>            <!-- Renderiza o input do campo -->
      </tr>
    {% endfor %}
  </table>
  <button type="submit">Salvar</button>
</form>
</div>
{% endblock content %}

chamados/templates/chamados/listar_chamados_nao_atendidos.html
{% extends 'base.html' %}
{% load static %}

{% block page_title %}Chamados Não Atendidos{% endblock page_title %}

{% block content %}
{% if existe_chamado_nao_atendido %}
<h2 style="text-align: center;"><img src="{% static 'img/chamado.png' %}" alt=""> Chamados não atendidos</h2>
<br>
<table class="table table-striped" style="text-align: center;">
    
    <thead>
        <tr>
            <th  scope="col">Título</th>
            <th  scope="col">Descrição</th>
            <th  scope="col">Data</th>
            <th  scope="col">Ação</th>
        </tr>
    </thead>
    <tbody class="table-group-divider">  
    {% for chamado in chamados_nao_atendidos %}
    <tr>
        <th scope="row">{{ chamado.titulo }}</th>
        <td>{{ chamado.descricao }}</td>
        <td>{{ chamado.data }}</td>
        <td><a href="{% url 'atualizar_chamado' chamado.id %}">Atualizar</a></td>
    </tr>
    {% endfor %}
</tbody>
</table>
</table>

{% else %}
<p>Todos os chamados foram atendidos.</p>
{% endif %}
{% endblock content %}

chamados/templates/chamados/tempo_medio_atendimento.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tempo Médio de Atendimento</title>
</head>
<body>
    <h1>Tempo Médio de Atendimento</h1>
    <table border="1">
        <thead>
            <tr>
                <th>Chamado</th>
                <th>Tempo de Atendimento</th>
            </tr>
        </thead>
        <tbody>
            {% for tempo_atendimento in tempos_atendimento %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ tempo_atendimento }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>